### ISSUE TITLE
Unable add M1S 2022

### ISSUE THREAD

**Issue by angus9487** [niceboygithub/AqaraGateway#100]
Aqara Gateway M1S 2022 (lumi.gateway.acn004, ZHWG20LM)
2022-04-29 16:29:06 INFO (MainThread) [custom_components.aqara_gateway.core.utils] lumi.gateway.acn004 4.0.1_0001 Linux detected
2022-04-29 16:30:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 653, in _send_frame
    self._write(header + message)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
<img width="579" alt="image" src="https://user-images.githubusercontent.com/21169287/165910499-959c4e76-4983-4f10-a730-48679e5f1f9a.png">

**Comment by niceboygithub** [comment]
M1S 2022 is not supported because it do not use mqtt.
