### ISSUE TITLE
ERROR (MainThread) [xiaomi_gateway] Got error element in data {"error":"Invalid key"}

### ISSUE THREAD

**Issue by kaczkalolo** [niceboygithub/AqaraGateway#114]
Hi All
I have:
Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

Aqara integration is stopping all the time after upgrade to the newest HA and all the devices are unavailable
with below errors:
ERROR (MainThread) [xiaomi_gateway] Got error element in data {"error":"Invalid key"}
ERROR (SyncWorker_7) [xiaomi_gateway] Got error element in data {"error":"Invalid key"}

When i reload the integration all thedevices come back for some time and then again it crashes...
Whenever i reload the integration i get another error:

Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:329
First occurred: 17:43:01 (3 occurrences)
Last logged: 17:48:36

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/xiaomi_gateway/__init__.py", line 180, in _listen_to_msg
    data, (ip_add, _) = self._mcastsocket.recvfrom(SOCKET_BUFSIZE)
OSError: [Errno 9] Bad file descriptor

**Comment by niceboygithub** [comment]
xiaomi_gateway?
