### ISSUE TITLE
Error: Uncaught thread exception

### ISSUE THREAD

**Issue by miniknife88** [niceboygithub/AqaraGateway#15]
Hassos ver: Home Assistant OS 5.12
Core ver: 2021.3.4

`2021-03-16 00:07:16 ERROR (Thread-7) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
self.loop_forever(retry_first_connection=True)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
rc = self.loop(timeout, max_packets)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
rc = self.loop_read(max_packets)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
rc = self._packet_read()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
rc = self._packet_handle()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
return self._handle_publish()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
self._handle_on_message(message)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
self.on_message(self, self._userdata, message)
File "/config/custom_components/aqara_gateway/core/gateway.py", line 422, in on_message
self._process_message(payload)
File "/config/custom_components/aqara_gateway/core/gateway.py", line 516, in _process_message
self._process_devices_info(
File "/config/custom_components/aqara_gateway/core/gateway.py", line 433, in _process_devices_info
self.devices.pop(value)
TypeError: unhashable type: 'dict'
2021-03-16 03:06:01 WARNING (zeroconf-Engine-252) [zeroconf] Choked at offset 32944 while unpacking b"\x00\x00\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x0fhomeassistant11\x05local\x00\x00\xff\x00\x012homeassistant11 [33ea4ea977414cb794194eb177730ee7]\x0c_workstation\x04_tcp\xc0\x1c\x00\xff\x00\x010homeassistant [33ea4ea977414cb794194eb177730ee7]\xc0Z\x00\xff\x00\x01\xc0'\x00\x10\x80\x01\x00\x00\x00x\x00\x01\x00\xc0'\x00!\x80\x01\x00\x00\x00x\x00\x1d\x00\x00\x00\x00\x00\x00\x0fhomeassistant11\x05local\x00\xc0\x0c\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\x01m"
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 745, in __init__
self.read_others()
File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 816, in read_others
domain = self.read_name()
File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 877, in read_name
length = self.data[off]
IndexError: index out of range`

**Comment by niceboygithub** [comment]
already try to fix.
Please test the latest commit
