### ISSUE TITLE
Could not parse JSON content: /config/custom_components/aqara_gateway/translations/ru.json

### ISSUE THREAD

**Issue by NikDevx** [niceboygithub/AqaraGateway#16]
```
Could not parse JSON content: /config/custom_components/aqara_gateway/translations/ru.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 9 (char 259)
```

**Comment by NikDevx** [comment]
**Fixed!**
Need to delete comma in `/config/custom_components/aqara_gateway/translations/ru.json`

Line | Col | Errors
-- | -- | --
4 | 213 | Unexpected comma.
7 | 455 | Unexpected comma.
