### ISSUE TITLE
Can add  Aqara aircondition P3 support ?

### ISSUE THREAD

**Issue by xStars** [niceboygithub/AqaraGateway#2]
I tested using https://github.com/niceboygithub/XiaomiGateway3
This version only needs a little modification to make it support lumi.aircondition.acn05

1. Open telent using python-maiio.
Miiocli gateway-- ip xxxx-- token xxxx raw_command set_ip_info'{"ssid": "\"\ "," pswd ":" 123123; passwd-d admin; echo enable > / sys/class/tty/tty/enable; telnetd "}'

2.
Use mosquitto extracted from mgl03 instead of p3 built-in mosquitto because the built-in version can only bind interface io.

3. Modify component-core-utils.py 
Modify gateway M2 to
'lumi.aircondition.acn05': ["Aqara", "Gateway M2", "KTBL12LM"].

Then add HA integration and it will work.

**Comment by xStars** [comment]
# cat /etc/build.prop
#ro.sys.name=Aqara-Hub-M2
#ro.sys.model=lumi.gateway.iragl01
#ro.sys.name=Aqara-Hub-M1S
#ro.sys.model=lumi.gateway.acn01
ro.sys.name=AC-Controller
ro.sys.model=lumi.aircondition.acn05
ro.sys.product=KTBL12LM
ro.sys.spu=ZHWG12LM
ro.sys.sku=AA003CNW01
ro.sys.ean13=6970504211889
ro.sys.manufacturer=Aqara
ro.sys.vendor=Lumi United Technology Co., Ltd.
ro.sys.fw_ver=3.0.7
ro.sys.build_num=0006
ro.sys.mi_fw_ver=3.0.0
ro.sys.mi_build_num=0079
ro.sys.hw_ver=1.0
ro.sys.acc_tags=red

**Comment by xStars** [comment]
it work aqara p3 
<img width="2535" alt="截屏2021-02-27 上午3 43 14" src="https://user-images.githubusercontent.com/4621709/109347498-398b3880-78ae-11eb-90ab-10ecd9d3a952.png">
<img width="2535" alt="截屏2021-02-27 上午3 43 52" src="https://user-images.githubusercontent.com/4621709/109347506-3bed9280-78ae-11eb-852d-dc54c63e83b1.png">
<img width="1040" alt="截屏2021-02-27 上午3 44 49" src="https://user-images.githubusercontent.com/4621709/109347509-3c862900-78ae-11eb-806c-8e7030346e99.png">

**Comment by niceboygithub** [comment]
Thanks for supporting and testing.

Can you help test with this repo?

**Comment by xStars** [comment]
I tested this repo.
When I use this repo, I can't find the device found in HA.

Enable debugger

2021-02-27 13:12:44 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140332572487152] Error handling message: Expecting property name enclosed in double quotes: line 5 column 9 (char 131)
2021-02-27 13:12:44 ERROR (SyncWorker_3) [homeassistant.util.json] Could not parse JSON content: /config/custom_components/aqara_gateway/translations/zh-Hans.json
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
return json.loads(fdesc.read()) # type: ignore
File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 9 (char 131)
2021-02-27 13:12:44 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140332572487152] Error handling message: Expecting property name enclosed in double quotes: line 5 column 9 (char 131)
2021-02-27 13:14:04 DEBUG (MainThread) [custom_components.aqara_gateway] SysInfo: {'installation_type': 'Home Assistant Supervised', 'version': '2021.2.3', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.7', 'docker': True, 'arch': 'x86_64', 'os_name': 'Linux', 'os_version': '4.19.0-13-amd64', 'supervisor': '2021.02.11', 'host_os': 'Debian GNU/Linux 10 (buster)', 'docker_version': '20.10.2', 'chassis': 'vm'}
2021-02-27 13:14:07 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000338,"did":"lumi.158d00023ec29b","time":1614402846674,"rssi":-53,"zseq":233,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:14:15 DEBUG (Thread-24) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: mosquitto is not running as public!
2021-02-27 13:14:15 DEBUG (Thread-24) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: Can't get devices: Expecting value: line 1 column 1 (char 0)
2021-02-27 13:14:30 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000339,"did":"lumi.158d00023ec29b","time":1614402869002,"rssi":-55,"zseq":234,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:14:35 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000340,"did":"lumi.158d00023ec29b","time":1614402874083,"rssi":-55,"zseq":235,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:14:38 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000341,"did":"lumi.158d0002c7e9bb","time":1614402877151,"rssi":-53,"zseq":49,"params":[{"res_name":"0.12.85","value":78.48}],"dev_src":"0"}
2021-02-27 13:14:44 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000342,"did":"lumi.158d00023ec29b","time":1614402883487,"rssi":-55,"zseq":236,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:14:53 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/recv {"cmd":"read","did":"lumi.0","id":1025,"params":[{"res_name":"8.0.2006"}],"source":"","time":1614402891997}
2021-02-27 13:14:53 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"read_rsp","id":1025,"did":"lumi.0","time":1614402892018,"zseq":0,"results":[{"res_name":"8.0.2006","value":36,"error_code":0}]}
2021-02-27 13:14:53 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: gateway <= [{'res_name': '8.0.2006', 'value': 36, 'error_code': 0}]
2021-02-27 13:14:58 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000343,"did":"lumi.158d0002c7e9bb","time":1614402897152,"rssi":-53,"zseq":51,"params":[{"res_name":"0.12.85","value":68.39}],"dev_src":"0"}
2021-02-27 13:15:08 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000344,"did":"lumi.158d0002c7e9bb","time":1614402907147,"rssi":-53,"zseq":52,"params":[{"res_name":"0.12.85","value":78.48}],"dev_src":"0"}
2021-02-27 13:15:18 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"heartbeat","id":2000000345,"time":1614402917328,"rssi":-47,"params":[{"did":"lumi.158d0002c7d951","time":1614402917328,"zseq":227,"res_list":[{"res_name":"4.1.85","value":0},{"res_name":"8.0.2006","value":22},{"res_name":"0.12.85","value":0},{"res_name":"0.13.85","value":187025.36},{"res_name":"8.0.2002","value":154},{"res_name":"8.0.2022","value":90},{"res_name":"8.0.2023","value":19},{"res_name":"8.0.2007","value":97}]}]}
2021-02-27 13:15:24 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000346,"did":"lumi.158d00023ec29b","time":1614402923745,"rssi":-56,"zseq":237,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:15:28 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000347,"did":"lumi.158d0002c7e9bb","time":1614402927149,"rssi":-54,"zseq":53,"params":[{"res_name":"0.12.85","value":68.39}],"dev_src":"0"}
2021-02-27 13:15:32 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000348,"did":"lumi.158d00023ec29b","time":1614402931584,"rssi":-53,"zseq":238,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:15:38 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000349,"did":"lumi.158d00023ec29b","time":1614402937337,"rssi":-52,"zseq":239,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:15:45 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000350,"did":"lumi.158d00023ec29b","time":1614402944058,"rssi":-55,"zseq":240,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:15:51 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000351,"did":"lumi.158d00023ec29b","time":1614402949850,"rssi":-57,"zseq":241,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:15:53 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/recv {"cmd":"read","did":"lumi.0","id":1026,"params":[{"res_name":"8.0.2006"}],"source":"","time":1614402951997}
2021-02-27 13:15:53 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"read_rsp","id":1026,"did":"lumi.0","time":1614402952017,"zseq":0,"results":[{"res_name":"8.0.2006","value":36,"error_code":0}]}
2021-02-27 13:15:53 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: gateway <= [{'res_name': '8.0.2006', 'value': 36, 'error_code': 0}]
2021-02-27 13:15:56 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000352,"did":"lumi.158d00023ec29b","time":1614402954995,"rssi":-49,"zseq":242,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:16:01 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000353,"did":"lumi.158d00023ec29b","time":1614402960642,"rssi":-55,"zseq":243,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:16:07 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000354,"did":"lumi.158d00023ec29b","time":1614402966275,"rssi":-59,"zseq":244,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:16:14 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"report","id":2000000355,"did":"lumi.158d00023ec29b","time":1614402972913,"rssi":-53,"zseq":245,"params":[{"res_name":"3.1.85","value":1}],"dev_src":"0"}
2021-02-27 13:16:21 DEBUG (Thread-25) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send

**Comment by xStars** [comment]
From the log, mqqt has been connected.

Using the command / data/bin/mosquitto-v on p3,can see
1614402761: New connection from 192.168.50.123 on port 1883.
1614402761: New client connected from 192.168.50.123 as auto-A2576D44-BE66-EF0E-2D00-BF8B7E2A07FD (p2, c1, k60).
1614402761: No will message specified.
1614402761: Sending CONNACK to auto-A2576D44-BE66-EF0E-2D00-BF8B7E2A07FD (0, 0)
1614402761: Received SUBSCRIBE from auto-A2576D44-BE66-EF0E-2D00-BF8B7E2A07FD
1614402761:     # (QoS 0)
1614402761: auto-A2576D44-BE66-EF0E-2D00-BF8B7E2A07FD 0 #
1614402761: Sending SUBACK to auto-A2576D44-BE66-EF0E-2D00-BF8B7E2A07FD
1614402763: Received PUBLISH from ZigbeeClient (d0, q0, r0, m0, 'zigbee/send', ... (160 bytes))
1614402763: Sending PUBLISH to zigbee_gateway_device (d0, q0, r0, m0, 'zigbee/send', ... (160 bytes))
1614402763: Sending PUBLISH to auto-A2576D44-BE66-EF0E-2D00-BF8B7E2A07FD (d0, q0, r0, m0, 'zigbee/send', ... (160 bytes))
1614402769: Received PUBLISH from ZigbeeClient (d0, q0, r0, m0, 'zigbee/send', ... (160 bytes))
1614402769: Sending PUBLISH to zigbee_gateway_device (d0, q0, r0, m0, 'zigbee/send', ... (160 bytes))
1614402769: Sending PUBLISH to auto-A2576D44-BE66-EF0E-2D00-BF8B7E2A07FD (d0, q0, r0, m0, 'zigbee/send', ... (160 bytes))

**Comment by niceboygithub** [comment]
Thanks for testing. You do great help.
I updated the latest commit.

**Comment by xStars** [comment]
/mnt/config/miio/device.conf 
/mnt/config/miio/device.conf
**There are no such file
modified /custom_components/aqara_gateway/core/gateway.py 
line 191 and line  219 Modify to
`elif 'lumi.gateway' in model or 'lumi.aircondition' in model :`
After completion, the device can be found and controlled in HA, but sometimes the zigbee, cannot be controlled and the pairing switch seems to be invalid.

this is p3 grop cmd**
[persist.app.cloud_provisioned]: [true]
[persist.app.hap_keepalive]: [true]
[persist.app.hap_provisioned]: [true]
[persist.app.ir.ac_mode]: [32]
[persist.app.ir.ac_status_0]: [50315f4d315f5432355f53335f443000]
[persist.app.ir.b_id]: [31383700]
[persist.app.ir.binding_state]: [31]
[persist.app.ir.cool_len]: [313000]
[persist.app.ir.cooling_temp]: [32352e303030303030]
[persist.app.ir.energy]: [323236393300]
[persist.app.ir.f_path_0]: [2f646174612f73746f726167652f6972...]
[persist.app.ir.f_r_id_0]: [313035303200]
[persist.app.ir.f_time]: [3136313335343639323900]
[persist.app.ir.heating_temp]: [32352e303030303030]
[persist.app.ir.load_power]: [0]
[persist.app.ir.match_m]: [3700]
[persist.app.ir.mode_id]: [3100]
[persist.app.ir.on_off_status]: [30]
[persist.app.ir.r_id]: [313035303200]
[persist.app.ir.range_id_0]: [7b226d61746368223a312c226d6f6465...]
[persist.app.ir.range_id_1]: [223a302c226469734c223a307d2c7b22...]
[persist.app.ir.relay_s]: [3000]
[persist.app.ir.rotation_speed]: [32]
[persist.app.ir.s_cfg_0]: [5b305d00]
[persist.app.ir.s_e_id]: [3100]
[persist.app.ir.s_e_p_id]: [3100]
[persist.app.ir.s_e_t_id]: [313500]
[persist.app.ir.swing_mode]: [31]
[persist.app.ir.type_id]: [3200]
[persist.app.miio_dtoken]: [xxxxxxxxxxxxxxxx]
[persist.app.miio_uid]: [888888888]
[persist.app.provision_wlan]: [true]
[persist.app.user_paired]: [true]
[persist.app.wifi_bssid]: [11:22:33:44:55:66]
[persist.app.wifi_mgmt]: [WPA]
[persist.app.wifi_passphrase]: [xxxxxxxxx]
[persist.app.wifi_ssid]: [xxxxxxxx]
[persist.sys.binding_did]: [lumi.158d00052b3ff9]
[persist.sys.binding_fw_ver]: [5]
[persist.sys.binding_ht]: [true]
[persist.sys.binding_model]: [lumi.weather.v1]
[persist.sys.binding_zb_ver]: [1.2]
[persist.sys.cloud]: [miot]
[persist.sys.coap_key]: [xxxxxxxxxxxxxxxxxxxxxx]
[persist.sys.did]: [lumi1.54ef44cac6a6]
[persist.sys.factory_passwd]: [123456789]
[persist.sys.factory_result]: [true]
[persist.sys.factory_ssid]: [Hardware_Automation]
[persist.sys.hap_code]: [123-45-678]
[persist.sys.hap_id]: [DV9I]
[persist.sys.hap_product]: [xxxxxxxxxxxxxxxx]
[persist.sys.hap_salt]: [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
[persist.sys.hap_verifier]: [xxxxxxxxxxxxxxxx...]
[persist.sys.lan_mac]: [11:22:33:44:55:66]
[persist.sys.lan_name]: [eth0]
[persist.sys.lan_supported]: [false]
[persist.sys.language]: [ch]
[persist.sys.miio_did]: [666666666]
[persist.sys.miio_key]: [Ekgg6k4T3XN4tRsZ]
[persist.sys.miio_mac]: [11:22:33:44:55:66]
[persist.sys.miio_vendor]: [lumi]
[persist.sys.model]: [lumi.aircondition.acn05]
[persist.sys.power_zero_off_value]: [21]
[persist.sys.power_zero_on_value]: [31]
[persist.sys.sn]: [SLAAC88888888888]
[persist.sys.temperature]: [26.5]
[persist.sys.volume]: [3]
[persist.sys.wlan_mac]: [11:22:33:44:55:66]
[persist.sys.wlan_mark]: [miap]
[persist.sys.wlan_name]: [wlan0]
[persist.sys.wlan_supported]: [true]
[persist.sys.zb30_auth]: [true]
[persist.sys.zb_pa]: [1]
[persist.sys.zb_ver]: [0515]
[ro.sys.name]: [AC-Controller]
[ro.sys.model]: [lumi.aircondition.acn05]
[ro.sys.product]: [KTBL12LM]
[ro.sys.spu]: [ZHWG12LM]
[ro.sys.sku]: [AA003CNW01]
[ro.sys.ean13]: [6970504211889]
[ro.sys.manufacturer]: [Aqara]
[ro.sys.vendor]: [Lumi United Technology Co., Ltd.]
[ro.sys.fw_ver]: [3.0.7]
[ro.sys.build_num]: [0006]
[ro.sys.mi_fw_ver]: [3.0.0]
[ro.sys.mi_build_num]: [0079]
[ro.sys.hw_ver]: [1.0]
[ro.sys.acc_tags]: [red]
[ro.sys.prop_port]: [56115]
[ro.sys.prop_valid]: [true]
[sys.router_host]: [192.168.50.1]
[sys.chip_temperature]: [36]

<img width="312" alt="QQ20210227-204820@2x" src="https://user-images.githubusercontent.com/4621709/109387630-7b16f480-793d-11eb-8a85-f32e7ef19168.png">
<img width="1952" alt="QQ20210227-204939@2x" src="https://user-images.githubusercontent.com/4621709/109387631-7ce0b800-793d-11eb-9810-4ebd018ef1c6.png">
<img width="390" alt="QQ20210227-205008@2x" src="https://user-images.githubusercontent.com/4621709/109387632-7d794e80-793d-11eb-9bd9-96206ad5b8cd.png">
<img width="483" alt="QQ20210227-205025@2x" src="https://user-images.githubusercontent.com/4621709/109387633-7e11e500-793d-11eb-8fa6-0db08c9e6ddd.png">

**Comment by niceboygithub** [comment]
Any logs about motion sensor?
Basic log and mqtt logs , HA logs are better

**Comment by xStars** [comment]
this is ha logs 
[home-assistant.log](https://github.com/niceboygithub/AqaraGateway/files/6055191/home-assistant.log)
and P3 does not support Illuminance, can be removed on p3
whe

**Comment by xStars** [comment]
Part of the capture in ha debug mode
[ha_debug.log](https://github.com/niceboygithub/AqaraGateway/files/6055269/ha_debug.log)

**Comment by niceboygithub** [comment]
Thanks for support!

**Comment by xStars** [comment]
Thank you. Now the component collapse problem has been solved and the control and update have been running without exception for some time, and it can be used normally on p3.
In addition, minor problems are known.
1. The pairing switch is invalid.
2. There is no light in p3, so there is no need to add rgb light.

**Comment by niceboygithub** [comment]
The pairing switch is working in M1S, M2, and G2H.
Can you send the log while using the pairing switch?
Thanks

**Comment by xStars** [comment]
**this is use pairing switch log**
switch open
2021-02-28 21:52:57 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: ioctl/recv {"cmd":"control","data":{"did":"lumi.0","paring":60},"rev":1,"id":55365}

switch close
2021-02-28 21:52:55 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: ioctl/recv {"cmd":"control","data":{"did":"lumi.0","paring":0},"rev":1,"id":14122}

**and this is use app pair log**
2021-02-28 21:45:25 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/recv {"cmd":"write","did":"lumi.0","id":3808,"params":[{"res_name":"8.0.2109","value":60}],"source":"","time":1614519924841}
[use_app_pair.log](https://github.com/niceboygithub/AqaraGateway/files/6056888/use_app_pair.log)

2021-02-28 21:45:25 DEBUG (Thread-6) [custom_components.aqara_gateway.core.gateway] 192.168.50.107: MQTT on_message: zigbee/send {"cmd":"write_rsp","id":3808,"time":1614519924872,"did":"lumi.0","zseq":0,"results":[{"res_name":"8.0.2109","value":60,"error_code":0}]}

**Comment by niceboygithub** [comment]
> 1. The pairing switch is invalid.

My fail. fix it with https://github.com/niceboygithub/AqaraGateway/commit/9aa8bdcee7b6510da9fca4131fc6c102c5e24b62

**Comment by xStars** [comment]
Thanks.this bug fixed.
