### ISSUE TITLE
Setup failed for custom integration 'aqara_gateway': Unable to import component: No module named 'imp'

### ISSUE THREAD

**Issue by sulliwane** [niceboygithub/AqaraGateway#248]
Hi, 

I recently get this error:
![image](https://github.com/niceboygithub/AqaraGateway/assets/1733686/02f41124-4c51-4f5f-b56e-10b739d32991)

![image](https://github.com/niceboygithub/AqaraGateway/assets/1733686/2627678f-fe37-4d38-8cc8-e375726bce87)

It seems related to the fact the HA is now using Python 3.12, which doesn't use 'imp' package anymore (but importlib instead, see: https://docs.python.org/3.11/library/imp.html#module-imp).

Also logs in plain text:
```
Logger: homeassistant.setup
Source: setup.py:316
First occurred: April 7, 2024 at 20:12:04 (2 occurrences)
Last logged: April 7, 2024 at 20:12:04

Setup failed for custom integration 'xiaomi_miot': Unable to import component: No module named 'imp'
Setup failed for custom integration 'aqara_gateway': Unable to import component: No module named 'imp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 979, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miot/__init__.py", line 32, in <module>
    from miio import (
  File "/usr/local/lib/python3.12/site-packages/miio/__init__.py", line 12, in <module>
    from miio.device import Device, DeviceStatus  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 13, in <module>
    from .miioprotocol import MiIOProtocol
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 13, in <module>
    import construct
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 316, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 997, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 989, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miot/__init__.py", line 32, in <module>
    from miio import (
  File "/usr/local/lib/python3.12/site-packages/miio/__init__.py", line 12, in <module>
    from miio.device import Device, DeviceStatus  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 13, in <module>
    from .miioprotocol import MiIOProtocol
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 13, in <module>
    import construct
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'
```

Here is my HA specs:
![image](https://github.com/niceboygithub/AqaraGateway/assets/1733686/8cc4b051-6c64-479c-ac93-f4085436d6aa)

Thanks for your help

**Comment by niceboygithub** [comment]
There is an another integration which installed the old miio . Please have a check.

**Comment by sulliwane** [comment]
Checked, this repo:
![Screenshot from 2024-05-12 20-32-48](https://github.com/niceboygithub/AqaraGateway/assets/1733686/3bee0036-2ca1-4394-8ebb-69d7e7b722fc)

And HACS installed repo:
![Screenshot from 2024-05-12 20-33-02](https://github.com/niceboygithub/AqaraGateway/assets/1733686/27b82821-c292-4ab7-9686-6e4542b9e622)

Same latest version. Also clicking on this button:
![image](https://github.com/niceboygithub/AqaraGateway/assets/1733686/22a62323-94f4-4f3a-920d-d1813cd98fe1)

Brings me to this repo.

Maybe it's worth mentioning that restarting one time will fail. After one failure, another restart will succeed. Then will fail. Then succeed. Every one in two restart fails/succeed.

So I always have to restart HA two times. 

Thanks for your help

**Comment by sulliwane** [comment]
Hey  @niceboygithub , could you clarify what github repo is the "old one" and which one is the "new one"?

Also, is it 'xiaomi_miot' that is supposed to install "aqara_gateway" or the other way around?

Thanks!

**Comment by sulliwane** [comment]
Ok, so seems I solved it doing this: https://github.com/al-one/hass-xiaomi-miot/issues/1526#issuecomment-2298802337

closing for now
