### ISSUE TITLE
New release broke the integration 

### ISSUE THREAD

**Issue by Kathou99** [niceboygithub/AqaraGateway#268]
Hi, did I am the only one the integration break after the new release?

```
Error setting up entry Aqara-Hub-M2-7AE9 for aqara_gateway
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aqara_gateway/__init__.py", line 51, in async_setup_entry
    raise ConfigEntryNotReady
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'ConfigEntryNotReady' is not defined
```

**Comment by niceboygithub** [comment]
That means your configuration for integration are missing. Please remove the integration and add again.

**Comment by ihaettypo** [comment]
Same problem

**Comment by Necroneco** [comment]
#264
