### ISSUE TITLE
升级HA之后报错

### ISSUE THREAD

**Issue by guoyuangy5** [niceboygithub/AqaraGateway#310]
Core
2024.11.0
Supervisor
2024.11.2
Operating System
13.2
Frontend
20241106.0

日志记录器: homeassistant.config_entries
来源: config_entries.py:635
首次出现: 08:06:43 (7 次总计出现)
上次记录: 08:09:16
Error setting up entry AC-Controller-EA86 for aqara_gateway
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aqara_gateway/__init__.py", line 67, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, DOMAINS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2237, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms
    import_future.result()
  [Previous line repeated 5 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1169, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1094, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1268, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1300, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/aqara_gateway/binary_sensor.py", line 9, in <module>
    from homeassistant.config import DATA_CUSTOMIZE
ImportError: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)

**Comment by mmib** [comment]
Same here after upgrade to HA 2024.11
`Error setting up entry Aqara-Hub-E1-B19A for aqara_gateway
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/aqara_gateway/__init__.py", line 67, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, DOMAINS)
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2237, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/loader.py", line 1181, in async_get_platforms
    import_future.result()
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/loader.py", line 1181, in async_get_platforms
    import_future.result()
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/loader.py", line 1181, in async_get_platforms
    import_future.result()
  [Previous line repeated 7 more times]
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/loader.py", line 1169, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/loader.py", line 1094, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/loader.py", line 1268, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/loader.py", line 1300, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/aqara_gateway/binary_sensor.py", line 9, in <module>
    from homeassistant.config import DATA_CUSTOMIZE
ImportError: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config.py)`

**Comment by ihaettypo** [comment]
Same here, thanks

**Comment by tidegu** [comment]
We are on the same boat bro!

**Comment by Lunmingpei** [comment]
same problem, cannot boot HA until I disable it

**Comment by niceboygithub** [comment]
fixed in 0.2.8
