### ISSUE TITLE
after a while，socket  (QBCZ15LM) unavailable

### ISSUE THREAD

**Issue by miniknife88** [niceboygithub/AqaraGateway#8]
After a while (about 1 hour)，socket change to unavailable
The message normal in the debug log，but socket state change to unavailable in ui
Currently only the socket type has this problem

Normal after reload integration

**Comment by niceboygithub** [comment]
Need yours confirm.
From your latest debug log, '4.2.85' is never reported in 'lumi.plug.sacn03'.
That's why the switch of socket become unavailable.
If there is no prop '4.2.85' in 'lumi.plug.sacn03', it shall be removed.

**Comment by miniknife88** [comment]
'4.2.85' is reported in 'lumi.plug.sacn03'，log:

` 2021-03-03 14:32:44  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_consumption | consumption <= {'switch': 1}
 2021-03-03 14:33:22  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/recv {"cmd":"write","did":"lumi.4cf8cdf3c87c700","id":9495,"params":[{"res_name":"4.2.85","value":1}]}
 2021-03-03 14:33:22  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"write_rsp","id":9495,"time":1614753202406,"did":"lumi.4cf8cdf3c87c700","zseq":78,"results":[{"res_name":"4.2.85","value":1,"error_code":0}]}
 2021-03-03 14:33:22  DEBUG  gateway  192.168.1.51: lumi.4cf8cdf3c87c700 lumi.plug.sacn03 <= {'switch_usb': 1} [1614753202.5732844]
 2021-03-03 14:33:22  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_power | power <= {'switch_usb': 1}
 2021-03-03 14:33:22  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_consumption | consumption <= {'switch_usb': 1}
 2021-03-03 14:33:22  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"write_ack","id":9495,"did":"lumi.4cf8cdf3c87c700","dev_src":"7","time":1614753202492,"rssi":-39,"zseq":79,"params":[{"res_name":"4.2.85","value":1}]}
 2021-03-03 14:33:22  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"report","id":9495,"did":"lumi.4cf8cdf3c87c700","time":1614753202495,"rssi":-39,"zseq":79,"params":[{"res_name":"4.2.85","value":1}],"dev_src":"0"}
 2021-03-03 14:33:22  DEBUG  gateway  192.168.1.51: lumi.4cf8cdf3c87c700 lumi.plug.sacn03 <= {'switch_usb': 1} [1614753202.667393]
 2021-03-03 14:33:22  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_power | power <= {'switch_usb': 1}
 2021-03-03 14:33:22  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_consumption | consumption <= {'switch_usb': 1}
 2021-03-03 14:33:25  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"heartbeat","id":2000022144,"time":1614753205284,"rssi":-50,"params":[{"did":"lumi.4cf8cdf3c7d74e7","time":1614753205284,"zseq":122,"res_list":[{"res_name":"8.0.2006","value":38},{"res_name":"8.0.2002","value":2},{"res_name":"8.0.2022","value":31},{"res_name":"8.0.2023","value":1},{"res_name":"4.1.85","value":0},{"res_name":"14.1.85","value":100},{"res_name":"14.2.85","value":178},{"res_name":"8.0.2036","value":54108},{"res_name":"8.0.2007","value":87}]}]}
 2021-03-03 14:33:25  DEBUG  gateway  192.168.1.51: lumi.4cf8cdf3c7d74e7 lumi.light.cwacn1 <= {'chip_temperature': 38, 'reset_cnt': 2, 'fw_ver': 31, 'hw_ver': 1, 'light': 0, 'brightness': 100, 'color_temp': 178, 'parent': 54108, 'lqi': 87} [1614753205.45164]
 2021-03-03 14:33:27  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"report","id":2000022145,"did":"lumi.4cf8cdf3c87c700","time":1614753207630,"rssi":-40,"zseq":162,"params":[{"res_name":"0.12.85","value":2.13}],"dev_src":"0"}
 2021-03-03 14:33:27  DEBUG  gateway  192.168.1.51: lumi.4cf8cdf3c87c700 lumi.plug.sacn03 <= {'load_power': 2.13} [1614753207.7974315]
 2021-03-03 14:33:27  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_power | power <= {'load_power': 2.13}
 2021-03-03 14:33:27  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_consumption | consumption <= {'load_power': 2.13}
 2021-03-03 14:33:28  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/recv {"cmd":"write","did":"lumi.4cf8cdf3c87c700","id":9496,"params":[{"res_name":"4.2.85","value":0}]}
 2021-03-03 14:33:28  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"write_rsp","id":9496,"time":1614753208216,"did":"lumi.4cf8cdf3c87c700","zseq":162,"results":[{"res_name":"4.2.85","value":0,"error_code":0}]}
 2021-03-03 14:33:28  DEBUG  gateway  192.168.1.51: lumi.4cf8cdf3c87c700 lumi.plug.sacn03 <= {'switch_usb': 0} [1614753208.3834798]
 2021-03-03 14:33:28  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_power | power <= {'switch_usb': 0}
 2021-03-03 14:33:28  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_consumption | consumption <= {'switch_usb': 0}
 2021-03-03 14:33:28  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"write_ack","id":9496,"did":"lumi.4cf8cdf3c87c700","dev_src":"7","time":1614753208675,"rssi":-39,"zseq":80,"params":[{"res_name":"4.2.85","value":0}]}
 2021-03-03 14:33:28  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"report","id":9496,"did":"lumi.4cf8cdf3c87c700","time":1614753208676,"rssi":-39,"zseq":80,"params":[{"res_name":"4.2.85","value":0}],"dev_src":"0"}
 2021-03-03 14:33:28  DEBUG  gateway  192.168.1.51: lumi.4cf8cdf3c87c700 lumi.plug.sacn03 <= {'switch_usb': 0} [1614753208.8451028]
 2021-03-03 14:33:28  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_power | power <= {'switch_usb': 0}
 2021-03-03 14:33:28  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_consumption | consumption <= {'switch_usb': 0}
 2021-03-03 14:33:33  DEBUG  gateway  192.168.1.51: MQTT on_message: zigbee/send {"cmd":"report","id":2000022146,"did":"lumi.4cf8cdf3c87c700","time":1614753213095,"rssi":-39,"zseq":164,"params":[{"res_name":"0.12.85","value":0}],"dev_src":"0"}
 2021-03-03 14:33:33  DEBUG  gateway  192.168.1.51: lumi.4cf8cdf3c87c700 lumi.plug.sacn03 <= {'load_power': 0} [1614753213.2685397]
 2021-03-03 14:33:33  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_power | power <= {'load_power': 0}
 2021-03-03 14:33:33  DEBUG  gateway  192.168.1.51: sensor.0x4cf8cdf3c87c700_consumption | consumption <= {'load_power': 0}`

From the code in utils.py

'4.1.85' and '4.2.85' is wrong

['4.1.85', 'neutral_0', 'switch', 'switch'],  # 4.1.85 is socket
['4.2.85', 'neutral_1', 'switch_usb', 'switch'], # 4.1.85 is usb socket

I will continue to test and feedback the test results later

**Comment by miniknife88** [comment]
[debug.log](https://github.com/niceboygithub/AqaraGateway/files/6074244/debug.log)

After some time, lumi.4cf8cdf3c87b18b offline
model : lumi.plug.sacn03

**Comment by miniknife88** [comment]
New problem, all devices are not updated and cannot be control

homeassistant log:

`2021-03-05 23:04:40 ERROR (Thread-7) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
self.loop_forever(retry_first_connection=True)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
rc = self.loop(timeout, max_packets)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
rc = self.loop_read(max_packets)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
rc = self._packet_read()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
rc = self._packet_handle()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
return self._handle_publish()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
self._handle_on_message(message)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
self.on_message(self, self._userdata, message)
File "/config/custom_components/aqara_gateway/core/gateway.py", line 386, in on_message
self.debug("MQTT on_message: {} {}".format(msg.topic, msg.payload.decode()))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 169: invalid continuation byte`

**Comment by niceboygithub** [comment]
> New problem, all devices are not updated and cannot be control
> 

Thanks, 
Let me add some error handling.
