### ISSUE TITLE
Cannot add Aqara Gateway M1S CN: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by tinymins** [niceboygithub/AqaraGateway#85]
I've following this steps: https://gist.github.com/InsaneWookie/1221cd6267745ea3c16f6a2a83ba3a44

Here is the telnet screenshot:
![image](https://user-images.githubusercontent.com/1808990/152913226-4adfe386-de07-4a2e-9141-069d973937bd.png)

Here is the miiocli info screenshot:
![image](https://user-images.githubusercontent.com/1808990/152913348-dae393f9-0711-40b1-91c2-aa753b2f45c9.png)

But in the last step, when I try to add integration, it says "Unknown error occurred":
![image](https://user-images.githubusercontent.com/1808990/152913444-57392f1b-794a-4cd1-83dd-01cfa602749a.png)

In the integrations configure page, I find a new integration added, but its status was "not loaded":
![image](https://user-images.githubusercontent.com/1808990/152913638-833fb54e-6820-4a77-930a-bc4acb1156bd.png)

I've checked the system logs, no message useful.

Could you help me out? I can not figure out what the problem is. I guess maybe my M1S hub firmware is too new?

**Comment by tinymins** [comment]
```
Logger: aiohttp.server
Source: custom_components/aqara_gateway/config_flow.py:273
Integration: Aqara Gateway ([documentation](https://github.com/niceboygithub/AqaraGateway), [issues](https://github.com/niceboygithub/AqaraGateway/issues))
First occurred: 11:30:01 (7 occurrences)
Last logged: 11:46:44

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 199, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/aqara_gateway/config_flow.py", line 273, in async_step_init
    self._host = self.config_entry.options[CONF_HOST]
KeyError: 'host'
```

Oh, I got one error message, that seems may be useful.

**Comment by niceboygithub** [comment]
Thanks for info.
Debugging

**Comment by niceboygithub** [comment]
Please try master branch to see if the issue be fixed

**Comment by tinymins** [comment]
> Please try master branch to see if the issue be fixed

Thanks for fixing.

But seems problem still exists, error message changed:

Add gateway UI screenshot:
![image](https://user-images.githubusercontent.com/1808990/153397992-e5ce654b-cc73-418a-9144-033b17a522a4.png)

Network screenshot:
![image](https://user-images.githubusercontent.com/1808990/153398538-46c03dae-e558-4512-a009-b0fa6df8647a.png)
![image](https://user-images.githubusercontent.com/1808990/153398706-f07ab7bf-dbb8-48c6-a086-67c73f513e95.png)
![image](https://user-images.githubusercontent.com/1808990/153398945-824141fb-a86d-40bd-bab5-7ae1dd9866ee.png)

Integration after add gateway screenshot:
![image](https://user-images.githubusercontent.com/1808990/153399483-199b1fad-eb90-472b-b592-e776be48c6a4.png)

Check code is latest master screenshot:
![image](https://user-images.githubusercontent.com/1808990/153400359-7f473481-49bb-4493-bd6c-3c299b02fcfb.png)

Check system logs:
```
Logger: aiohttp.server
Source: custom_components/aqara_gateway/config_flow.py:273
Integration: aqara_gateway ([documentation](https://github.com/niceboygithub/AqaraGateway), [issues](https://github.com/niceboygithub/AqaraGateway/issues))
First occurred: 19:27:52 (2 occurrences)
Last logged: 19:28:02

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 199, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/aqara_gateway/config_flow.py", line 273, in async_step_init
    self._host = self.config_entry.options[CONF_HOST]
KeyError: 'host'
```

**Comment by niceboygithub** [comment]
wired.

Can you show the settings in your /config/.storage/core.config_entries?
like this
![image](https://user-images.githubusercontent.com/74046071/153417451-58e25a70-9dae-4c8b-a1d7-f81d53841c32.png)

**Comment by tinymins** [comment]
Here it is.

![image](https://user-images.githubusercontent.com/1808990/153562016-4a311a7d-2394-462d-8194-7553c1a2a42c.png)

btw, I have added this `aqara gateway` by miio and homekit, is that matters?

![image](https://user-images.githubusercontent.com/1808990/153562671-8bf149fa-087a-4dd8-9b4c-141814216085.png)

**Comment by niceboygithub** [comment]
> Here it is.
> 
> ![image](https://user-images.githubusercontent.com/1808990/153562016-4a311a7d-2394-462d-8194-7553c1a2a42c.png)

From the [code](https://github.com/niceboygithub/AqaraGateway/blob/67ed8597a00c78902e3e51d112787d3af0142ce7/custom_components/aqara_gateway/__init__.py#L47) , the entry data will be copy to entry option while setup entry. What magic you did?

> 
> btw, I have added this `aqara gateway` by miio and homekit, will that cause trouble?
> 

They shall be not effect.

**Comment by tinymins** [comment]
I dont know 😂, maybe we can have a remote control on my computer to start a remote debug if you have time.

**Comment by tinymins** [comment]
Wait... I forgot to say. Every time when I try to add the `Aqara Gateway`, after `commit` button clicked, the `HA` system will get suspended. A message "Lost connection..." will be displayed at left bottom corner.

Is that normal?

![image](https://user-images.githubusercontent.com/1808990/153633075-2e412a03-098c-417c-a1fe-25c32e472b5e.png)

**Comment by tinymins** [comment]
After a reboot, the gateway got connected... that's really wired, is reboot necessary after add new aqara gateway integration?
![5F3B9F04-8EBE-4E8A-A470-AFE2615A927A](https://user-images.githubusercontent.com/1808990/153696437-89012661-a219-4d43-8802-493c80514436.png)
